using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CRMS.Utils
{
    public class Crms100
    {
        public  String Id { get; set; }
        public String Code { get; set; }
        public String CustomerId { get; set; }
        public String CustomerAccountNumber { get; set; }
        public String CustomerName { get; set; }
        public String GovernmentCode { get; set; }
        public String LegalStatus { get; set; }
        public String CreditType { get; set; }
        public String CreditPurposeByBusinessLines { get; set; }
        public String CreditPurposeByBusinessLinesSubsector { get; set; }
        public decimal CreditLimit { get; set; }
        public  decimal OutstandingAmount { get; set; }
        public  String FeeType1 { get; set; }
        public decimal FeeAmount1 { get; set; }
        public String FeeType2 { get; set; }
        public  decimal FeeAmount2 { get; set; }
        public String FeeType3 { get; set; }
        public decimal FeeAmount3 { get; set; }
        public String FeeType4 { get; set; }
        public decimal FeeAmount4 { get; set; }
        public String FeeType5 { get; set; }
        public decimal FeeAmount5 { get; set; }
        public String FeeType6 { get; set; }
        public decimal FeeAmount6 { get; set; }
        public String FeeType7 { get; set; }
        public decimal FeeAmount7 { get; set; }
        public String FeeType8 { get; set; }
        public decimal FeeAmount8 { get; set; }
        public String FeeType9 { get; set; }
        public decimal FeeAmount9 { get; set; }
        public String FeeType10 { get; set; }
        public decimal FeeAmount10 { get; set; }
        public String FeeType11 { get; set; }
        public decimal FeeAmount11 { get; set; }
        public String FeeType12 { get; set; }
        public decimal FeeAmount12 { get; set; }
        public String FeeType13 { get; set; }
        public decimal FeeAmount13 { get; set; }
        public String FeeType14 { get; set; }
        public decimal FeeAmount14 { get; set; }
        public String FeeType15 { get; set; }
        public decimal FeeAmount15 { get; set; }
        public String FeeType16 { get; set; }
        public decimal FeeAmount16 { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public int Tenor { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public String RepaymentAgreementMode { get; set; }
        public String SpecialisedLoan { get; set; }
        public int SpecialisedLoanPeriod { get; set; }
        public decimal InterestRate { get; set; }
        public String CollateralPresent1 { get; set; }
        public String CollateralSecure1 { get; set; }
        public String SecurityType1 { get; set; }
        public String CollateralSecure2 { get; set; }
        public String SecurityType2 { get; set; }
        public String CollateralSecure3 { get; set; }
        public String SecurityType3 { get; set; }
        public String CollateralSecure4 { get; set; }
        public String SecurityType4 { get; set; }
        public String CollateralSecure5 { get; set; }
        public String SecurityType5 { get; set; }
        public String CollateralSecure6 { get; set; }
        public String SecurityType6 { get; set; }
        public String CollateralSecure7 { get; set; }
        public String SecurityType7 { get; set; }
        public String CollateralSecure8 { get; set; }
        public String SecurityType8 { get; set; }
        public String CollateralSecure9 { get; set; }
        public String SecurityType9 { get; set; }
        public String CollateralSecure10 { get; set; }
        public String SecurityType10 { get; set; }
        public String RepaymentSource { get; set; }
        public String Syndication { get; set; }
        public String SyndicationStatus { get; set; }
        public String SyndicationReferenceNumber { get; set; }
        public String InputterId { get; set; }
        public DateTime? InputterDateStamp { get; set; }
        public String ModifierId { get; set; }
        public String ModifierDateStamp { get; set; }
        public String CrmsRefNumber { get; set; }
        public String LoanRefNumber { get; set; }
    }

    public class Crms200
    {
        public String Id { get; set; }
        public String Code { get; set; }
        public String CustomerId { get; set; }
        public String CustomerAccountNumber { get; set; }
        public String CustomerName { get; set; }
        public String GovernmentMdaTin { get; set; }
        public String LegalStatus { get; set; }
        public String CreditType { get; set; }
        public String CreditPurposeByBusinessLines { get; set; }
        public String CreditPurposeByBusinessLinesSubsector { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal OutstandingAmount { get; set; }
        public String FeeType1 { get; set; }
        public decimal FeeAmount1 { get; set; }
        public String FeeType2 { get; set; }
        public decimal FeeAmount2 { get; set; }
        public String FeeType3 { get; set; }
        public decimal FeeAmount3 { get; set; }
        public String FeeType4 { get; set; }
        public decimal FeeAmount4 { get; set; }
        public String FeeType5 { get; set; }
        public decimal FeeAmount5 { get; set; }
        public String FeeType6 { get; set; }
        public decimal FeeAmount6 { get; set; }
        public String FeeType7 { get; set; }
        public decimal FeeAmount7 { get; set; }
        public String FeeType8 { get; set; }
        public decimal FeeAmount8 { get; set; }
        public String FeeType9 { get; set; }
        public decimal FeeAmount9 { get; set; }
        public String FeeType10 { get; set; }
        public decimal FeeAmount10 { get; set; }
        public String FeeType11 { get; set; }
        public decimal FeeAmount11 { get; set; }
        public String FeeType12 { get; set; }
        public decimal FeeAmount12 { get; set; }
        public String FeeType13 { get; set; }
        public decimal FeeAmount13 { get; set; }
        public String FeeType14 { get; set; }
        public decimal FeeAmount14 { get; set; }
        public String FeeType15 { get; set; }
        public decimal FeeAmount15 { get; set; }
        public String FeeType16 { get; set; }
        public decimal FeeAmount16 { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public int Tenor { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public String RepaymentAgreementMode { get; set; }
        public String PerformanceRepaymentStatus { get; set; }
        public String SpecialisedLoan { get; set; }
        public int SpecialisedLoanPeriod { get; set; }
        public decimal InterestRate { get; set; }
        public String CollateralPresent1 { get; set; }
        public String CollateralSecure1 { get; set; }
        public String SecurityType1 { get; set; }
        public String CollateralSecure2 { get; set; }
        public String SecurityType2 { get; set; }
        public String CollateralSecure3 { get; set; }
        public String SecurityType3 { get; set; }
        public String CollateralSecure4 { get; set; }
        public String SecurityType4 { get; set; }
        public String CollateralSecure5 { get; set; }
        public String SecurityType5 { get; set; }
        public String CollateralSecure6 { get; set; }
        public String SecurityType6 { get; set; }
        public String CollateralSecure7 { get; set; }
        public String SecurityType7 { get; set; }
        public String CollateralSecure8 { get; set; }
        public String SecurityType8 { get; set; }
        public String CollateralSecure9 { get; set; }
        public String SecurityType9 { get; set; }
        public String CollateralSecure10 { get; set; }
        public String SecurityType10 { get; set; }
        public String RepaymentSource { get; set; }
        public String Syndication { get; set; }
        public String SyndicationStatus { get; set; }
        public String SyndicationReferenceNumber { get; set; }
        public String InputterId { get; set; }
        public DateTime? InputterDateStamp { get; set; }
        public String ModifierId { get; set; }
        public String ModifierDateStamp { get; set; }
        public String CrmsRefNumber { get; set; }
        public String LoanRefNumber { get; set; }
    }

    public class Crms300
    {
        public String Id { get; set; }
        public String Code { get; set; }
        public String CustomerId { get; set; }
        public String CustomerAccountNumber { get; set; }
        public String CustomerName { get; set; }
        public String UniqueIdentificationType { get; set; }
        public String UniqueIdentificationNumber { get; set; }
        public String CreditType { get; set; }
        public String CreditPurposeByBusinessLines { get; set; }
        public String CreditPurposeByBusinessLinesSubsector { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal OutstandingAmount { get; set; }
        public String FeeType1 { get; set; }
        public decimal FeeAmount1 { get; set; }
        public String FeeType2 { get; set; }
        public decimal FeeAmount2 { get; set; }
        public String FeeType3 { get; set; }
        public decimal FeeAmount3 { get; set; }
        public String FeeType4 { get; set; }
        public decimal FeeAmount4 { get; set; }
        public String FeeType5 { get; set; }
        public decimal FeeAmount5 { get; set; }
        public String FeeType6 { get; set; }
        public decimal FeeAmount6 { get; set; }
        public String FeeType7 { get; set; }
        public decimal FeeAmount7 { get; set; }
        public String FeeType8 { get; set; }
        public decimal FeeAmount8 { get; set; }
        public String FeeType9 { get; set; }
        public decimal FeeAmount9 { get; set; }
        public String FeeType10 { get; set; }
        public decimal FeeAmount10 { get; set; }
        public String FeeType11 { get; set; }
        public decimal FeeAmount11 { get; set; }
        public String FeeType12 { get; set; }
        public decimal FeeAmount12 { get; set; }
        public String FeeType13 { get; set; }
        public decimal FeeAmount13 { get; set; }
        public String FeeType14 { get; set; }
        public decimal FeeAmount14 { get; set; }
        public String FeeType15 { get; set; }
        public decimal FeeAmount15 { get; set; }
        public String FeeType16 { get; set; }
        public decimal FeeAmount16 { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public int Tenor { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public String RepaymentAgreementMode { get; set; }
        public decimal InterestRate { get; set; }
        public String BeneficiaryAccountNumber { get; set; }
        public String LocationOfBeneficiary { get; set; }
        public String RelationshipType { get; set; }
        public String FundingSourceCategory { get; set; }
        public String EcciNumber { get; set; }
        public String FundingSource { get; set; }
        public String LegalStatus { get; set; }
        public String ClassificationByBusinessLines { get; set; }
        public String ClassificationByBusinessLinesSubsector { get; set; }
        public String SpecialisedLoan { get; set; }
        public int SpecialisedLoanPeriod { get; set; }
        public String DirectorIdType1 { get; set; }
        public String DirectorIdNumber1 { get; set; }
        public String DirectorIdEmail1 { get; set; }
        public String DirectorIdType2 { get; set; }
        public String DirectorIdNumber2 { get; set; }
        public String DirectorIdEmail2 { get; set; }
        public String DirectorIdType3 { get; set; }
        public String DirectorIdNumber3 { get; set; }
        public String DirectorIdEmail3 { get; set; }
        public String DirectorIdType4 { get; set; }
        public String DirectorIdNumber4 { get; set; }
        public String DirectorIdEmail4 { get; set; }
        public String DirectorIdType5 { get; set; }
        public String DirectorIdNumber5 { get; set; }
        public String DirectorIdEmail5 { get; set; }
        public String Syndication { get; set; }
        public String SyndicationStatus { get; set; }
        public String SyndicationReferenceNumber { get; set; }
        public String CollateralPresent1 { get; set; }
        public String CollateralSecure1 { get; set; }
        public String SecurityType1 { get; set; }
        public String AddressOfSecurity1 { get; set; }
        public String OwnerOfSecurity1 { get; set; }
        public String SecurityIdType1 { get; set; }
        public String SecurityIdNumber1 { get; set; }
        public String CollateralSecure2 { get; set; }
        public String SecurityType2 { get; set; }
        public String AddressOfSecurity2 { get; set; }
        public String OwnerOfSecurity2 { get; set; }
        public String SecurityIdType2 { get; set; }
        public String SecurityIdNumber2 { get; set; }
        public String CollateralSecure3 { get; set; }
        public String SecurityType3 { get; set; }
        public String AddressOfSecurity3 { get; set; }
        public String OwnerOfSecurity3 { get; set; }
        public String SecurityIdType3 { get; set; }
        public String SecurityIdNumber3 { get; set; }
        public String CollateralSecure4 { get; set; }
        public String SecurityType4 { get; set; }
        public String AddressOfSecurity4 { get; set; }
        public String OwnerOfSecurity4 { get; set; }
        public String SecurityIdType4 { get; set; }
        public String SecurityIdNumber4 { get; set; }
        public String CollateralSecure5 { get; set; }
        public String SecurityType5 { get; set; }
        public String AddressOfSecurity5 { get; set; }
        public String OwnerOfSecurity5 { get; set; }
        public String SecurityIdType5 { get; set; }
        public String SecurityIdNumber5 { get; set; }
        public String CollateralSecure6 { get; set; }
        public String SecurityType6 { get; set; }
        public String AddressOfSecurity6 { get; set; }
        public String OwnerOfSecurity6 { get; set; }
        public String SecurityIdType6 { get; set; }
        public String SecurityIdNumber6 { get; set; }
        public String CollateralSecure7 { get; set; }
        public String SecurityType7 { get; set; }
        public String AddressOfSecurity7 { get; set; }
        public String OwnerOfSecurity7 { get; set; }
        public String SecurityIdType7 { get; set; }
        public String SecurityIdNumber7 { get; set; }
        public String CollateralSecure8 { get; set; }
        public String SecurityType8 { get; set; }
        public String AddressOfSecurity8 { get; set; }
        public String OwnerOfSecurity8 { get; set; }
        public String SecurityIdType8 { get; set; }
        public String SecurityIdNumber8 { get; set; }
        public String CollateralSecure9 { get; set; }
        public String SecurityType9 { get; set; }
        public String AddressOfSecurity9 { get; set; }
        public String OwnerOfSecurity9 { get; set; }
        public String SecurityIdType9 { get; set; }
        public String SecurityIdNumber9 { get; set; }
        public String CollateralSecure10 { get; set; }
        public String SecurityType10 { get; set; }
        public String AddressOfSecurity10 { get; set; }
        public String OwnerOfSecurity10 { get; set; }
        public String SecurityIdType10 { get; set; }
        public String SecurityIdNumber10 { get; set; }
        public String Guarantee1 { get; set; }
        public String GuaranteeType1 { get; set; }
        public String GuaranteeIdType1 { get; set; }
        public String GuaranteeIdNumber1 { get; set; }
        public decimal AmountGuranteed1 { get; set; }
        public String GuaranteeType2 { get; set; }
        public String GuaranteeIdType2 { get; set; }
        public String GuaranteeIdNumber2 { get; set; }
        public decimal AmountGuranteed2 { get; set; }
        public String GuaranteeType3 { get; set; }
        public String GuaranteeIdType3 { get; set; }
        public String GuaranteeIdNumber3 { get; set; }
        public decimal AmountGuranteed3 { get; set; }
        public String GuaranteeType4 { get; set; }
        public String GuaranteeIdType4 { get; set; }
        public String GuaranteeIdNumber4 { get; set; }
        public decimal AmountGuranteed4 { get; set; }
        public String GuaranteeType5 { get; set; }
        public String GuaranteeIdType5 { get; set; }
        public String GuaranteeIdNumber5 { get; set; }
        public decimal AmountGuranteed5 { get; set; }
        public String InputterId { get; set; }
        public DateTime? InputterDateStamp { get; set; }
        public String ModifierId { get; set; }
        public String ModifierDateStamp { get; set; }
        public String CrmsRefNumber { get; set; }
        public String LoanRefNumber { get; set; }
    }

    public class Crms400A
    {
        public String Id { get; set; }
        public String Code { get; set; }
        public String CustomerId { get; set; }
        public String CustomerAccountNumber { get; set; }
        public String CustomerName { get; set; }
        public String UniqueIdentificationType { get; set; }
        public String UniqueIdentificationNumber { get; set; }
        public String CrmsReferenceNumber { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public int Tenor { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public String InputterId { get; set; }
        public DateTime? InputterDateStamp { get; set; }
        public String ModifierId { get; set; }
        public String ModifierDateStamp { get; set; }
        public String CrmsRefNumber { get; set; }
        public String LoanRefNumber { get; set; }
    }

    public class Crms400B
    {
        public String Id { get; set; }
        public String Code { get; set; }
        public String CustomerId { get; set; }
        public String CustomerAccountNumber { get; set; }
        public String CustomerName { get; set; }
        public String UniqueIdentificationType { get; set; }
        public String UniqueIdentificationNumber { get; set; }
        public String CrmsReferenceNumber { get; set; }
        public String CreditType { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal OutstandingAmount { get; set; }
        public String FeeType1 { get; set; }
        public decimal FeeAmount1 { get; set; }
        public String FeeType2 { get; set; }
        public decimal FeeAmount2 { get; set; }
        public String FeeType3 { get; set; }
        public decimal FeeAmount3 { get; set; }
        public String FeeType4 { get; set; }
        public decimal FeeAmount4 { get; set; }
        public String FeeType5 { get; set; }
        public decimal FeeAmount5 { get; set; }
        public String FeeType6 { get; set; }
        public decimal FeeAmount6 { get; set; }
        public String FeeType7 { get; set; }
        public decimal FeeAmount7 { get; set; }
        public String FeeType8 { get; set; }
        public decimal FeeAmount8 { get; set; }
        public String FeeType9 { get; set; }
        public decimal FeeAmount9 { get; set; }
        public String FeeType10 { get; set; }
        public decimal FeeAmount10 { get; set; }
        public String FeeType11 { get; set; }
        public decimal FeeAmount11 { get; set; }
        public String FeeType12 { get; set; }
        public decimal FeeAmount12 { get; set; }
        public String FeeType13 { get; set; }
        public decimal FeeAmount13 { get; set; }
        public String FeeType14 { get; set; }
        public decimal FeeAmount14 { get; set; }
        public String FeeType15 { get; set; }
        public decimal FeeAmount15 { get; set; }
        public String FeeType16 { get; set; }
        public decimal FeeAmount16 { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public int Tenor { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public String RepaymentAgreementMode { get; set; }
        public String PerformanceRepaymentStatus { get; set; }
        public String ReasonForRestructuring { get; set; }
        public decimal InterestRate { get; set; }
        public String BeneficiaryAccountNumber { get; set; }
        public String LocationOfBeneficiary { get; set; }
        public String RelationshipType { get; set; }
        public String FundingSourceCategory { get; set; }
        public String EcciNumber { get; set; }
        public String FundingSource { get; set; }
        public String SpecialisedLoan { get; set; }
        public int SpecialisedLoanPeriod { get; set; }
        public String DirectorIdType1 { get; set; }
        public String DirectorIdNumber1 { get; set; }
        public String DirectorIdEmail1 { get; set; }
        public String DirectorIdType2 { get; set; }
        public String DirectorIdNumber2 { get; set; }
        public String DirectorIdEmail2 { get; set; }
        public String DirectorIdType3 { get; set; }
        public String DirectorIdNumber3 { get; set; }
        public String DirectorIdEmail3 { get; set; }
        public String DirectorIdType4 { get; set; }
        public String DirectorIdNumber4 { get; set; }
        public String DirectorIdEmail4 { get; set; }
        public String DirectorIdType5 { get; set; }
        public String DirectorIdNumber5 { get; set; }
        public String DirectorIdEmail5 { get; set; }
        public String CollateralPresent1 { get; set; }
        public String CollateralSecure1 { get; set; }
        public String SecurityType1 { get; set; }
        public String AddressOfSecurity1 { get; set; }
        public String OwnerOfSecurity1 { get; set; }
        public String SecurityIdType1 { get; set; }
        public String SecurityIdNumber1 { get; set; }
        public String CollateralSecure2 { get; set; }
        public String SecurityType2 { get; set; }
        public String AddressOfSecurity2 { get; set; }
        public String OwnerOfSecurity2 { get; set; }
        public String SecurityIdType2 { get; set; }
        public String SecurityIdNumber2 { get; set; }
        public String CollateralSecure3 { get; set; }
        public String SecurityType3 { get; set; }
        public String AddressOfSecurity3 { get; set; }
        public String OwnerOfSecurity3 { get; set; }
        public String SecurityIdType3 { get; set; }
        public String SecurityIdNumber3 { get; set; }
        public String CollateralSecure4 { get; set; }
        public String SecurityType4 { get; set; }
        public String AddressOfSecurity4 { get; set; }
        public String OwnerOfSecurity4 { get; set; }
        public String SecurityIdType4 { get; set; }
        public String SecurityIdNumber4 { get; set; }
        public String CollateralSecure5 { get; set; }
        public String SecurityType5 { get; set; }
        public String AddressOfSecurity5 { get; set; }
        public String OwnerOfSecurity5 { get; set; }
        public String SecurityIdType5 { get; set; }
        public String SecurityIdNumber5 { get; set; }
        public String CollateralSecure6 { get; set; }
        public String SecurityType6 { get; set; }
        public String AddressOfSecurity6 { get; set; }
        public String OwnerOfSecurity6 { get; set; }
        public String SecurityIdType6 { get; set; }
        public String SecurityIdNumber6 { get; set; }
        public String CollateralSecure7 { get; set; }
        public String SecurityType7 { get; set; }
        public String AddressOfSecurity7 { get; set; }
        public String OwnerOfSecurity7 { get; set; }
        public String SecurityIdType7 { get; set; }
        public String SecurityIdNumber7 { get; set; }
        public String CollateralSecure8 { get; set; }
        public String SecurityType8 { get; set; }
        public String AddressOfSecurity8 { get; set; }
        public String OwnerOfSecurity8 { get; set; }
        public String SecurityIdType8 { get; set; }
        public String SecurityIdNumber8 { get; set; }
        public String CollateralSecure9 { get; set; }
        public String SecurityType9 { get; set; }
        public String AddressOfSecurity9 { get; set; }
        public String OwnerOfSecurity9 { get; set; }
        public String SecurityIdType9 { get; set; }
        public String SecurityIdNumber9 { get; set; }
        public String CollateralSecure10 { get; set; }
        public String SecurityType10 { get; set; }
        public String AddressOfSecurity10 { get; set; }
        public String OwnerOfSecurity10 { get; set; }
        public String SecurityIdType10 { get; set; }
        public String SecurityIdNumber10 { get; set; }
        public String Guarantee1 { get; set; }
        public String GuaranteeType1 { get; set; }
        public String GuaranteeIdType1 { get; set; }
        public String GuaranteeIdNumber1 { get; set; }
        public decimal AmountGuranteed1 { get; set; }
        public String GuaranteeType2 { get; set; }
        public String GuaranteeIdType2 { get; set; }
        public String GuaranteeIdNumber2 { get; set; }
        public decimal AmountGuranteed2 { get; set; }
        public String GuaranteeType3 { get; set; }
        public String GuaranteeIdType3 { get; set; }
        public String GuaranteeIdNumber3 { get; set; }
        public decimal AmountGuranteed3 { get; set; }
        public String GuaranteeType4 { get; set; }
        public String GuaranteeIdType4 { get; set; }
        public String GuaranteeIdNumber4 { get; set; }
        public decimal AmountGuranteed4 { get; set; }
        public String GuaranteeType5 { get; set; }
        public String GuaranteeIdType5 { get; set; }
        public String GuaranteeIdNumber5 { get; set; }
        public decimal AmountGuranteed5 { get; set; }
        public String InputterId { get; set; }
        public DateTime? InputterDateStamp { get; set; }
        public String ModifierId { get; set; }
        public String ModifierDateStamp { get; set; }
        public String CrmsRefNumber { get; set; }
        public String LoanRefNumber { get; set; }
    }

    public class Crms600
    {
        public String Id { get; set; }
        public String Code { get; set; }
        public String CustomerId { get; set; }
        public String CustomerAccountNumber { get; set; }
        public String CustomerName { get; set; }
        public String SyndicationReferenceNumber { get; set; }
        public String SyndicationName { get; set; }
        public decimal SyndicationTotalAmount { get; set; }
        public String ParticipatingBankCode { get; set; }
        public String InputterId { get; set; }
        public DateTime? InputterDateStamp { get; set; }
        public String ModifierId { get; set; }
        public String ModifierDateStamp { get; set; }
        public String CrmsRefNumber { get; set; }
        public String LoanRefNumber { get; set; }
    }

    public class Crms700
    {
        public String Id { get; set; }
        public String Code { get; set; }
        public String CustomerId { get; set; }
        public String CustomerAccountNumber { get; set; }
        public String CustomerName { get; set; }
        public String UniqueIdentificationType { get; set; }
        public String UniqueIdentificationNumber { get; set; }
        public String CrmsReferenceNumber { get; set; }
        public String CreditPurposeByBusinessLines { get; set; }
        public String CreditPurposeByBusinessLinesSubsector { get; set; }
        public String FeeType1 { get; set; }
        public decimal FeeAmount1 { get; set; }
        public String FeeType2 { get; set; }
        public decimal FeeAmount2 { get; set; }
        public String FeeType3 { get; set; }
        public decimal FeeAmount3 { get; set; }
        public String FeeType4 { get; set; }
        public decimal FeeAmount4 { get; set; }
        public String FeeType5 { get; set; }
        public decimal FeeAmount5 { get; set; }
        public String FeeType6 { get; set; }
        public decimal FeeAmount6 { get; set; }
        public String FeeType7 { get; set; }
        public decimal FeeAmount7 { get; set; }
        public String FeeType8 { get; set; }
        public decimal FeeAmount8 { get; set; }
        public String FeeType9 { get; set; }
        public decimal FeeAmount9 { get; set; }
        public String FeeType10 { get; set; }
        public decimal FeeAmount10 { get; set; }
        public String FeeType11 { get; set; }
        public decimal FeeAmount11 { get; set; }
        public String FeeType12 { get; set; }
        public decimal FeeAmount12 { get; set; }
        public String FeeType13 { get; set; }
        public decimal FeeAmount13 { get; set; }
        public String FeeType14 { get; set; }
        public decimal FeeAmount14 { get; set; }
        public String FeeType15 { get; set; }
        public decimal FeeAmount15 { get; set; }
        public String FeeType16 { get; set; }
        public decimal FeeAmount16 { get; set; }
        public int Tenor { get; set; }
        public String BeneficiaryAccountNumber { get; set; }
        public String LocationOfBeneficiary { get; set; }
        public String RelationshipType { get; set; }
        public String FundingSourceCategory { get; set; }
        public String EcciNumber { get; set; }
        public String FundingSource { get; set; }
        public String LegalStatus { get; set; }
        public String ClassificationByBusinessLines { get; set; }
        public String ClassificationByBusinessLinesSubsector { get; set; }
        public String SpecialisedLoan { get; set; }
        public int SpecialisedLoanPeriod { get; set; }
        public String DirectorIdType1 { get; set; }
        public String DirectorIdNumber1 { get; set; }
        public String DirectorIdEmail1 { get; set; }
        public String DirectorIdType2 { get; set; }
        public String DirectorIdNumber2 { get; set; }
        public String DirectorIdEmail2 { get; set; }
        public String DirectorIdType3 { get; set; }
        public String DirectorIdNumber3 { get; set; }
        public String DirectorIdEmail3 { get; set; }
        public String DirectorIdType4 { get; set; }
        public String DirectorIdNumber4 { get; set; }
        public String DirectorIdEmail4 { get; set; }
        public String DirectorIdType5 { get; set; }
        public String DirectorIdNumber5 { get; set; }
        public String DirectorIdEmail5 { get; set; }
        public String Syndication { get; set; }
        public String SyndicationStatus { get; set; }
        public String SyndicationName { get; set; }
        public decimal SyndicationTotalAmount { get; set; }
        public String SyndicationReferenceNumber { get; set; }
        public String CollateralPresent1 { get; set; }
        public String CollateralSecure1 { get; set; }
        public String SecurityType1 { get; set; }
        public String AddressOfSecurity1 { get; set; }
        public String OwnerOfSecurity1 { get; set; }
        public String SecurityIdType1 { get; set; }
        public String SecurityIdNumber1 { get; set; }
        public String CollateralSecure2 { get; set; }
        public String SecurityType2 { get; set; }
        public String AddressOfSecurity2 { get; set; }
        public String OwnerOfSecurity2 { get; set; }
        public String SecurityIdType2 { get; set; }
        public String SecurityIdNumber2 { get; set; }
        public String CollateralSecure3 { get; set; }
        public String SecurityType3 { get; set; }
        public String AddressOfSecurity3 { get; set; }
        public String OwnerOfSecurity3 { get; set; }
        public String SecurityIdType3 { get; set; }
        public String SecurityIdNumber3 { get; set; }
        public String CollateralSecure4 { get; set; }
        public String SecurityType4 { get; set; }
        public String AddressOfSecurity4 { get; set; }
        public String OwnerOfSecurity4 { get; set; }
        public String SecurityIdType4 { get; set; }
        public String SecurityIdNumber4 { get; set; }
        public String CollateralSecure5 { get; set; }
        public String SecurityType5 { get; set; }
        public String AddressOfSecurity5 { get; set; }
        public String OwnerOfSecurity5 { get; set; }
        public String SecurityIdType5 { get; set; }
        public String SecurityIdNumber5 { get; set; }
        public String CollateralSecure6 { get; set; }
        public String SecurityType6 { get; set; }
        public String AddressOfSecurity6 { get; set; }
        public String OwnerOfSecurity6 { get; set; }
        public String SecurityIdType6 { get; set; }
        public String SecurityIdNumber6 { get; set; }
        public String CollateralSecure7 { get; set; }
        public String SecurityType7 { get; set; }
        public String AddressOfSecurity7 { get; set; }
        public String OwnerOfSecurity7 { get; set; }
        public String SecurityIdType7 { get; set; }
        public String SecurityIdNumber7 { get; set; }
        public String CollateralSecure8 { get; set; }
        public String SecurityType8 { get; set; }
        public String AddressOfSecurity8 { get; set; }
        public String OwnerOfSecurity8 { get; set; }
        public String SecurityIdType8 { get; set; }
        public String SecurityIdNumber8 { get; set; }
        public String CollateralSecure9 { get; set; }
        public String SecurityType9 { get; set; }
        public String AddressOfSecurity9 { get; set; }
        public String OwnerOfSecurity9 { get; set; }
        public String SecurityIdType9 { get; set; }
        public String SecurityIdNumber9 { get; set; }
        public String CollateralSecure10 { get; set; }
        public String SecurityType10 { get; set; }
        public String AddressOfSecurity10 { get; set; }
        public String OwnerOfSecurity10 { get; set; }
        public String SecurityIdType10 { get; set; }
        public String SecurityIdNumber10 { get; set; }
        public String Guarantee1 { get; set; }
        public String GuaranteeType1 { get; set; }
        public String GuaranteeIdType1 { get; set; }
        public String GuaranteeIdNumber1 { get; set; }
        public decimal AmountGuranteed1 { get; set; }
        public String GuaranteeType2 { get; set; }
        public String GuaranteeIdType2 { get; set; }
        public String GuaranteeIdNumber2 { get; set; }
        public decimal AmountGuranteed2 { get; set; }
        public String GuaranteeType3 { get; set; }
        public String GuaranteeIdType3 { get; set; }
        public String GuaranteeIdNumber3 { get; set; }
        public decimal AmountGuranteed3 { get; set; }
        public String GuaranteeType4 { get; set; }
        public String GuaranteeIdType4 { get; set; }
        public String GuaranteeIdNumber4 { get; set; }
        public decimal AmountGuranteed4 { get; set; }
        public String GuaranteeType5 { get; set; }
        public String GuaranteeIdType5 { get; set; }
        public String GuaranteeIdNumber5 { get; set; }
        public decimal AmountGuranteed5 { get; set; }
        public String InputterId { get; set; }
        public DateTime? InputterDateStamp { get; set; }
        public String ModifierId { get; set; }
        public String ModifierDateStamp { get; set; }
        public String CrmsRefNumber { get; set; }
        public String LoanRefNumber { get; set; }
    }

}