//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMSEntities : DbContext
    {
        public CRMSEntities()
            : base("name=CRMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CRMS_100> CRMS_100 { get; set; }
        public DbSet<CRMS_200> CRMS_200 { get; set; }
        public DbSet<CRMS_300> CRMS_300 { get; set; }
        public DbSet<CRMS_400A> CRMS_400A { get; set; }
        public DbSet<CRMS_400B> CRMS_400B { get; set; }
        public DbSet<CRMS_600> CRMS_600 { get; set; }
        public DbSet<CRMS_700> CRMS_700 { get; set; }
    }
}
