//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMS_100
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Customer_ID { get; set; }
        public string Customer_Account_Number { get; set; }
        public string Customer_Name { get; set; }
        public string Government_Code { get; set; }
        public string Legal_Status { get; set; }
        public string Credit_Type { get; set; }
        public string Credit_Purpose_By_Business_Lines { get; set; }
        public string Credit_Purpose_By_Business_Lines_Subsector { get; set; }
        public decimal Credit_Limit { get; set; }
        public decimal Outstanding_Amount { get; set; }
        public string Fee_Type1 { get; set; }
        public decimal Fee_Amount1 { get; set; }
        public string Fee_Type2 { get; set; }
        public Nullable<decimal> Fee_Amount2 { get; set; }
        public string Fee_Type3 { get; set; }
        public Nullable<decimal> Fee_Amount3 { get; set; }
        public string Fee_Type4 { get; set; }
        public Nullable<decimal> Fee_Amount4 { get; set; }
        public string Fee_Type5 { get; set; }
        public Nullable<decimal> Fee_Amount5 { get; set; }
        public string Fee_Type6 { get; set; }
        public Nullable<decimal> Fee_Amount6 { get; set; }
        public string Fee_Type7 { get; set; }
        public Nullable<decimal> Fee_Amount7 { get; set; }
        public string Fee_Type8 { get; set; }
        public Nullable<decimal> Fee_Amount8 { get; set; }
        public string Fee_Type9 { get; set; }
        public Nullable<decimal> Fee_Amount9 { get; set; }
        public string Fee_Type10 { get; set; }
        public Nullable<decimal> Fee_Amount10 { get; set; }
        public string Fee_Type11 { get; set; }
        public Nullable<decimal> Fee_Amount11 { get; set; }
        public string Fee_Type12 { get; set; }
        public Nullable<decimal> Fee_Amount12 { get; set; }
        public string Fee_Type13 { get; set; }
        public Nullable<decimal> Fee_Amount13 { get; set; }
        public string Fee_Type14 { get; set; }
        public Nullable<decimal> Fee_Amount14 { get; set; }
        public string Fee_Type15 { get; set; }
        public Nullable<decimal> Fee_Amount15 { get; set; }
        public string Fee_Type16 { get; set; }
        public Nullable<decimal> Fee_Amount16 { get; set; }
        public System.DateTime Effective_Date { get; set; }
        public decimal Tenor { get; set; }
        public System.DateTime Expiry_Date { get; set; }
        public string Repayment_Agreement_Mode { get; set; }
        public string Specialised_Loan { get; set; }
        public Nullable<decimal> Specialised_Loan_Period { get; set; }
        public decimal Interest_Rate { get; set; }
        public string Collateral_Present1 { get; set; }
        public string Collateral_Secure1 { get; set; }
        public string Security_Type1 { get; set; }
        public string Collateral_Secure2 { get; set; }
        public string Security_Type2 { get; set; }
        public string Collateral_Secure3 { get; set; }
        public string Security_Type3 { get; set; }
        public string Collateral_Secure4 { get; set; }
        public string Security_Type4 { get; set; }
        public string Collateral_Secure5 { get; set; }
        public string Security_Type5 { get; set; }
        public string Collateral_Secure6 { get; set; }
        public string Security_Type6 { get; set; }
        public string Collateral_Secure7 { get; set; }
        public string Security_Type7 { get; set; }
        public string Collateral_Secure8 { get; set; }
        public string Security_Type8 { get; set; }
        public string Collateral_Secure9 { get; set; }
        public string Security_Type9 { get; set; }
        public string Collateral_Secure10 { get; set; }
        public string Security_Type10 { get; set; }
        public string Repayment_Source { get; set; }
        public string Syndication { get; set; }
        public string Syndication_Status { get; set; }
        public string Syndication_Reference_Number { get; set; }
        public string Inputter_ID { get; set; }
        public Nullable<System.DateTime> Inputter_Date_Stamp { get; set; }
        public string Modifier_ID { get; set; }
        public Nullable<System.DateTime> Modifier_Date_Stamp { get; set; }
        public string CRMS_Ref_Number { get; set; }
        public string Loan_Ref_Number { get; set; }
    }
}
