//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMS_700
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Customer_ID { get; set; }
        public string Customer_Account_Number { get; set; }
        public string Customer_Name { get; set; }
        public string Unique_Identifcation_Type { get; set; }
        public string Unique_Identifcation_Number { get; set; }
        public string CRMS_Reference_Number { get; set; }
        public string Credit_Purpose_By_Business_Lines { get; set; }
        public string Credit_Purpose_By_Business_Lines_Subsector { get; set; }
        public string Fee_Type1 { get; set; }
        public decimal Fee_Amount1 { get; set; }
        public string Fee_Type2 { get; set; }
        public Nullable<decimal> Fee_Amount2 { get; set; }
        public string Fee_Type3 { get; set; }
        public Nullable<decimal> Fee_Amount3 { get; set; }
        public string Fee_Type4 { get; set; }
        public Nullable<decimal> Fee_Amount4 { get; set; }
        public string Fee_Type5 { get; set; }
        public Nullable<decimal> Fee_Amount5 { get; set; }
        public string Fee_Type6 { get; set; }
        public Nullable<decimal> Fee_Amount6 { get; set; }
        public string Fee_Type7 { get; set; }
        public Nullable<decimal> Fee_Amount7 { get; set; }
        public string Fee_Type8 { get; set; }
        public Nullable<decimal> Fee_Amount8 { get; set; }
        public string Fee_Type9 { get; set; }
        public Nullable<decimal> Fee_Amount9 { get; set; }
        public string Fee_Type10 { get; set; }
        public Nullable<decimal> Fee_Amount10 { get; set; }
        public string Fee_Type11 { get; set; }
        public Nullable<decimal> Fee_Amount11 { get; set; }
        public string Fee_Type12 { get; set; }
        public Nullable<decimal> Fee_Amount12 { get; set; }
        public string Fee_Type13 { get; set; }
        public Nullable<decimal> Fee_Amount13 { get; set; }
        public string Fee_Type14 { get; set; }
        public Nullable<decimal> Fee_Amount14 { get; set; }
        public string Fee_Type15 { get; set; }
        public Nullable<decimal> Fee_Amount15 { get; set; }
        public string Fee_Type16 { get; set; }
        public Nullable<decimal> Fee_Amount16 { get; set; }
        public decimal Tenor { get; set; }
        public string Beneficiary_Account_Number { get; set; }
        public string Location_of_Beneficiary { get; set; }
        public string Relationship_Type { get; set; }
        public string Company_Size { get; set; }
        public string Funding_Source_Category { get; set; }
        public string ECCI_Number { get; set; }
        public string Funding_Source { get; set; }
        public string Legal_Status { get; set; }
        public string Classification_By_Business_Lines { get; set; }
        public string Classification_By_Business_Lines_Subsector { get; set; }
        public string Specialised_Loan { get; set; }
        public Nullable<decimal> Specialised_Loan_Period { get; set; }
        public string Director_Id_Type1 { get; set; }
        public string Director_Id_Number1 { get; set; }
        public string Director_Id_Email1 { get; set; }
        public string Director_Id_Type2 { get; set; }
        public string Director_Id_Number2 { get; set; }
        public string Director_Id_Email2 { get; set; }
        public string Director_Id_Type3 { get; set; }
        public string Director_Id_Number3 { get; set; }
        public string Director_Id_Email3 { get; set; }
        public string Director_Id_Type4 { get; set; }
        public string Director_Id_Number4 { get; set; }
        public string Director_Id_Email4 { get; set; }
        public string Director_Id_Type5 { get; set; }
        public string Director_Id_Number5 { get; set; }
        public string Director_Id_Email5 { get; set; }
        public string Syndication { get; set; }
        public string Syndication_Status { get; set; }
        public string Syndication_Name { get; set; }
        public Nullable<decimal> Syndication_Total_Amount { get; set; }
        public string Syndication_Reference_Number { get; set; }
        public string Collateral_Present1 { get; set; }
        public string Collateral_Secure1 { get; set; }
        public string Security_Type1 { get; set; }
        public string Address_of_Security1 { get; set; }
        public string Owner_of_Security1 { get; set; }
        public string Security_Id_Type1 { get; set; }
        public string Security_Id_Number1 { get; set; }
        public string Collateral_Secure2 { get; set; }
        public string Security_Type2 { get; set; }
        public string Address_of_Security2 { get; set; }
        public string Owner_of_Security2 { get; set; }
        public string Security_Id_Type2 { get; set; }
        public string Security_Id_Number2 { get; set; }
        public string Collateral_Secure3 { get; set; }
        public string Security_Type3 { get; set; }
        public string Address_of_Security3 { get; set; }
        public string Owner_of_Security3 { get; set; }
        public string Security_Id_Type3 { get; set; }
        public string Security_Id_Number3 { get; set; }
        public string Collateral_Secure4 { get; set; }
        public string Security_Type4 { get; set; }
        public string Address_of_Security4 { get; set; }
        public string Owner_of_Security4 { get; set; }
        public string Security_Id_Type4 { get; set; }
        public string Security_Id_Number4 { get; set; }
        public string Collateral_Secure5 { get; set; }
        public string Security_Type5 { get; set; }
        public string Address_of_Security5 { get; set; }
        public string Owner_of_Security5 { get; set; }
        public string Security_Id_Type5 { get; set; }
        public string Security_Id_Number5 { get; set; }
        public string Collateral_Secure6 { get; set; }
        public string Security_Type6 { get; set; }
        public string Address_of_Security6 { get; set; }
        public string Owner_of_Security6 { get; set; }
        public string Security_Id_Type6 { get; set; }
        public string Security_Id_Number6 { get; set; }
        public string Collateral_Secure7 { get; set; }
        public string Security_Type7 { get; set; }
        public string Address_of_Security7 { get; set; }
        public string Owner_of_Security7 { get; set; }
        public string Security_Id_Type7 { get; set; }
        public string Security_Id_Number7 { get; set; }
        public string Collateral_Secure8 { get; set; }
        public string Security_Type8 { get; set; }
        public string Address_of_Security8 { get; set; }
        public string Owner_of_Security8 { get; set; }
        public string Security_Id_Type8 { get; set; }
        public string Security_Id_Number8 { get; set; }
        public string Collateral_Secure9 { get; set; }
        public string Security_Type9 { get; set; }
        public string Address_of_Security9 { get; set; }
        public string Owner_of_Security9 { get; set; }
        public string Security_Id_Type9 { get; set; }
        public string Security_Id_Number9 { get; set; }
        public string Collateral_Secure10 { get; set; }
        public string Security_Type10 { get; set; }
        public string Address_of_Security10 { get; set; }
        public string Owner_of_Security10 { get; set; }
        public string Security_Id_Type10 { get; set; }
        public string Security_Id_Number10 { get; set; }
        public string Guarantee1 { get; set; }
        public string Guarantee_Type1 { get; set; }
        public string Guarantor_Id_Type1 { get; set; }
        public string Guarantor_Id_Number1 { get; set; }
        public Nullable<decimal> Amount_Guaranteed1 { get; set; }
        public string Guarantee_Type2 { get; set; }
        public string Guarantor_Id_Type2 { get; set; }
        public string Guarantor_Id_Number2 { get; set; }
        public Nullable<decimal> Amount_Guaranteed2 { get; set; }
        public string Guarantee_Type3 { get; set; }
        public string Guarantor_Id_Type3 { get; set; }
        public string Guarantor_Id_Number3 { get; set; }
        public Nullable<decimal> Amount_Guaranteed3 { get; set; }
        public string Guarantee_Type4 { get; set; }
        public string Guarantor_Id_Type4 { get; set; }
        public string Guarantor_Id_Number4 { get; set; }
        public Nullable<decimal> Amount_Guaranteed4 { get; set; }
        public string Guarantee_Type5 { get; set; }
        public string Guarantor_Id_Type5 { get; set; }
        public string Guarantor_Id_Number5 { get; set; }
        public Nullable<decimal> Amount_Guaranteed5 { get; set; }
        public string Inputter_ID { get; set; }
        public Nullable<System.DateTime> Inputter_Date_Stamp { get; set; }
        public string Modifier_ID { get; set; }
        public Nullable<System.DateTime> Modifier_Date_Stamp { get; set; }
        public string CRMS_Ref_Number { get; set; }
        public string Loan_Ref_Number { get; set; }
    }
}
