//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMS.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com.ecobank.basis.authentication/", ConfigurationName="ServiceReference1.ADAuthenticatorSoap")]
    public interface ADAuthenticatorSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://com.ecobank.basis.authentication/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.ecobank.basis.authentication/HelloWorld", ReplyAction="*")]
        CRMS.ServiceReference1.HelloWorldResponse HelloWorld(CRMS.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.ecobank.basis.authentication/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<CRMS.ServiceReference1.HelloWorldResponse> HelloWorldAsync(CRMS.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://com.ecobank.basis.authentication/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://com.ecobank.basis.authentication/getUserStatus", ReplyAction="*")]
        CRMS.ServiceReference1.getUserStatusResponse getUserStatus(CRMS.ServiceReference1.getUserStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.ecobank.basis.authentication/getUserStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<CRMS.ServiceReference1.getUserStatusResponse> getUserStatusAsync(CRMS.ServiceReference1.getUserStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://com.ecobank.basis.authentication/", Order=0)]
        public CRMS.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CRMS.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://com.ecobank.basis.authentication/", Order=0)]
        public CRMS.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CRMS.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.ecobank.basis.authentication/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserStatus", Namespace="http://com.ecobank.basis.authentication/", Order=0)]
        public CRMS.ServiceReference1.getUserStatusRequestBody Body;
        
        public getUserStatusRequest() {
        }
        
        public getUserStatusRequest(CRMS.ServiceReference1.getUserStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.ecobank.basis.authentication/")]
    public partial class getUserStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getUserStatusRequestBody() {
        }
        
        public getUserStatusRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserStatusResponse", Namespace="http://com.ecobank.basis.authentication/", Order=0)]
        public CRMS.ServiceReference1.getUserStatusResponseBody Body;
        
        public getUserStatusResponse() {
        }
        
        public getUserStatusResponse(CRMS.ServiceReference1.getUserStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://com.ecobank.basis.authentication/")]
    public partial class getUserStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserStatusResult;
        
        public getUserStatusResponseBody() {
        }
        
        public getUserStatusResponseBody(string getUserStatusResult) {
            this.getUserStatusResult = getUserStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ADAuthenticatorSoapChannel : CRMS.ServiceReference1.ADAuthenticatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ADAuthenticatorSoapClient : System.ServiceModel.ClientBase<CRMS.ServiceReference1.ADAuthenticatorSoap>, CRMS.ServiceReference1.ADAuthenticatorSoap {
        
        public ADAuthenticatorSoapClient() {
        }
        
        public ADAuthenticatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ADAuthenticatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADAuthenticatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADAuthenticatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRMS.ServiceReference1.HelloWorldResponse CRMS.ServiceReference1.ADAuthenticatorSoap.HelloWorld(CRMS.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CRMS.ServiceReference1.HelloWorldRequest inValue = new CRMS.ServiceReference1.HelloWorldRequest();
            inValue.Body = new CRMS.ServiceReference1.HelloWorldRequestBody();
            CRMS.ServiceReference1.HelloWorldResponse retVal = ((CRMS.ServiceReference1.ADAuthenticatorSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRMS.ServiceReference1.HelloWorldResponse> CRMS.ServiceReference1.ADAuthenticatorSoap.HelloWorldAsync(CRMS.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRMS.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            CRMS.ServiceReference1.HelloWorldRequest inValue = new CRMS.ServiceReference1.HelloWorldRequest();
            inValue.Body = new CRMS.ServiceReference1.HelloWorldRequestBody();
            return ((CRMS.ServiceReference1.ADAuthenticatorSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRMS.ServiceReference1.getUserStatusResponse CRMS.ServiceReference1.ADAuthenticatorSoap.getUserStatus(CRMS.ServiceReference1.getUserStatusRequest request) {
            return base.Channel.getUserStatus(request);
        }
        
        public string getUserStatus(string username, string password) {
            CRMS.ServiceReference1.getUserStatusRequest inValue = new CRMS.ServiceReference1.getUserStatusRequest();
            inValue.Body = new CRMS.ServiceReference1.getUserStatusRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            CRMS.ServiceReference1.getUserStatusResponse retVal = ((CRMS.ServiceReference1.ADAuthenticatorSoap)(this)).getUserStatus(inValue);
            return retVal.Body.getUserStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRMS.ServiceReference1.getUserStatusResponse> CRMS.ServiceReference1.ADAuthenticatorSoap.getUserStatusAsync(CRMS.ServiceReference1.getUserStatusRequest request) {
            return base.Channel.getUserStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRMS.ServiceReference1.getUserStatusResponse> getUserStatusAsync(string username, string password) {
            CRMS.ServiceReference1.getUserStatusRequest inValue = new CRMS.ServiceReference1.getUserStatusRequest();
            inValue.Body = new CRMS.ServiceReference1.getUserStatusRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((CRMS.ServiceReference1.ADAuthenticatorSoap)(this)).getUserStatusAsync(inValue);
        }
    }
}
